name: CI

on:  # We are very liberal in terms of triggering builds. This should be revisited if we start seeing a lot of queueing
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  java_default_distribution: corretto
  java_default_version: 11

jobs:
  build-jars:
    runs-on: ubuntu-latest
    name: Build JARs
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Build JARs
        run: make jar
      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: async-profiler-jars
          path: build/jar/*
          if-no-files-found: error
  build-and-upload-binaries:
    strategy:
      matrix:
        include:
          - runson:
              display: macos
              name: macos-13
              java-version: 17
              java-distribution: corretto
    runs-on: ${{ matrix.runson.name }}
    name: "Build and unit test (${{ matrix.runson.display }})"
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-distribution || env.java_default_distribution }}
          java-version: ${{ matrix.java-version || env.java_default_version }}
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Build and unit test
        id: build
        run: |
          set -x
          HASH=${GITHUB_SHA:0:7}
          case "${{ matrix.runson.display }}" in
            macos*)
              make COMMIT_TAG=$HASH test TESTS=wall -j
            ;;
            *)
              make COMMIT_TAG=$HASH CC=/usr/local/musl/bin/musl-gcc release coverage -j
              echo "debug_archive=$(find . -type f -name "async-profiler-*-debug*" -exec basename {} \;)" >> $GITHUB_OUTPUT
            ;;
          esac
          echo "archive=$(find . -type f -name "async-profiler-*" -not -name "*-debug*" -exec basename {} \;)" >> $GITHUB_OUTPUT
        shell: bash
        env:
          GITHUB_SHA: ${{ github.sha }}
